# Site settings
title: "Rehanul Islam"
description: "A resume of Rehanul Islam known as DT "

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "true"
resume_name: "SM Rehanul Islam"
resume_title: "Full Stack web & Game Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email: "callmedt2005@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "+880-1315849244"
resume_contact_address: "Plot#4 , Road - 13, Adabor, Mohammadpur, Dhaka, Bangladesh"

resume_header_contact_info: "Plot#4 , Road - 13, Adabor, Mohammadpur, Dhaka, Bangladesh • +880-1315849244 • callmedt2005@gmail.com"
display_header_contact_info: "false"

resume_header_intro: "<p>As a Class XI student at Hamdard Public College in Dhaka, Bangladesh, my passion lies in the world of Computer Science and Engineering (CSE). Proficient in C, HTML, CSS, JavaScript, Python, Lua, and SQL, I blend technical expertise with a flair for design. My immediate career goal is to excel in web development, leveraging my skills to create impactful and user-centric digital experiences. Eager to collaborate on innovative projects and contribute to the tech industry's evolution.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: true
resume_section_recognition: true
resume_section_links: true
resume_section_associations: true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/TheDT01"
  resume_twitter_url: "https://twitter.com/rehanul92824"
  resume_dribbble_url: "https://dribbble.com/rehan_dt"
  resume_facebook_url: "https://www.facebook.com/rehanul.dt"
  resume_linkedin_url: "https://www.linkedin.com/in/rehanul-islam-dt-146666300/"
  resume_instagram_url: "https://www.instagram.com/rehan_d.t/"
  resume_website_url: "http://dt-fortune.com"
  resume_medium_url: "https://medium.com/@callmedt2005"
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
